# Generated by Django 5.2.10 on 2026-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('GERENTE', 'Gerente de Proyectos'), ('TRABAJADOR', 'Trabajador'), ('INVITADO', 'Invitado')], default='INVITADO', max_length=20, verbose_name='Rol'),
        ),
    ]
